install most things with mise, nix for the rest

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,17 +2,26 @@
 
 set -euo pipefail
 
-# Install pkgx 
+# Install pkgx for sheebang deps (https://github.com/pkgxdev/pkgx?tab=readme-ov-file#scripting)
 if ! command -v pkgx > /dev/null; then
   curl -fsS https://pkgx.sh | sh
 fi
-# Use pkgm for userland packages not available in Mise
-pkgm install git-crypt
 
 # Install and initialize chezmoi in one go
 if ! command -v chezmoi > /dev/null; then
   sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:nimser/private-dotfiles-devcontainer.git
 fi
 
-echo "Finished cloning chezmoi"
+# Install nix for dependencies that don't have a binary on github (would use mise otherwise)
+if ! command -v nix-env &>/dev/null; then
+  echo "nix-env command not found. Attempting to install Nix..."
+  sh <(curl -L https://nixos.org/nix/install) --daemon --yes
+  source /etc/profile.d/nix.sh
+fi
+# Set system type if not provided via cli
+export SYSTEM_TYPE=${SYSTEM_TYPE:-server}
+# Install all packages defined in config.nix
+nix-env -iA nixpkgs.myPackages --impure
+
+echo "Finished setting up dotfiles"
 exit 0
